# Generated by Django 3.1.1 on 2020-09-08 18:21

from django.db import migrations, models
import streamfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', streamfield.fields.StreamField(blank=True, default='[]')),
            ],
        ),
    ]
